

FROM jupyter/scipy-notebook:2ce7c06a61a1 

USER $NB_USER

# Install TensorFlow: 
RUN pip install tensorflow==2.0.0

# Install PyTorch libraries:
#RUN pip install https://download.pytorch.org/whl/cpu/torch-1.0.1.post2-cp37-cp37m-linux_x86_64.whl 
#RUN pip install torchvision==0.4.0
#RUN pip install torchsummary==1.5.1

# Install NLP libraries: 
#RUN pip install nltk==3.4.5
#RUN pip install gensim==3.8.1
#RUN pip install spacy==2.2.1
#RUN python -m spacy download en_core_web_sm

# Install Reinforcement Learning library:
#RUN pip install gym==0.12.5

# Install for Object Detection notebook: 
#RUN pip install opencv-python==4.1.2.30

#downgrade 
RUN pip install markupsafe==2.0.1

RUN pip install appnope==0.1.0
RUN pip install astroid==2.4.1
RUN pip install attrs==19.3.0
RUN pip install backcall==0.2.0
RUN pip install bleach==3.1.5
RUN pip install cycler==0.10.0
RUN pip install decorator==4.4.2
RUN pip install defusedxml==0.6.0
RUN pip install entrypoints==0.3
RUN pip install importlib-metadata==1.7.0
#RUN pip install ipykernel==5.3.4
#RUN pip install ipython==7.16.1
#RUN pip install ipython-genutils==0.2.0
RUN pip install isort==4.3.21
RUN pip install jedi==0.17.2
RUN pip install Jinja2==2.11.2
RUN pip install jsonschema==3.2.0
#RUN pip install jupyter-client==6.1.6
#RUN pip install jupyter-contrib-core==0.3.3
#RUN pip install jupyter-contrib-nbextensions==0.5.1
#RUN pip install jupyter-core==4.6.3
#RUN pip install jupyter-highlight-selected-word==0.2.0
#RUN pip install jupyter-latex-envs==1.4.6
#RUN pip install jupyter-nbextensions-configurator==0.4.1
RUN pip install kiwisolver==1.2.0
RUN pip install latexcodec==2.0.1
RUN pip install lazy-object-proxy==1.4.3
RUN pip install lxml==4.6.3
#RUN pip install MarkupSafe==1.1.1
RUN pip install matplotlib==3.2.1
RUN pip install mccabe==0.6.1
RUN pip install mistune==0.8.4
RUN pip install nbconvert==5.6.1
RUN pip install nbformat==5.0.7
RUN pip install notebook==6.0.3
RUN pip install numpy==1.18.1
RUN pip install packaging==20.4
RUN pip install pandocfilters==1.4.2
RUN pip install parso==0.7.1
RUN pip install pexpect==4.8.0
RUN pip install pickleshare==0.7.5
RUN pip install Pillow==7.0.0
RUN pip install prometheus-client==0.8.0
RUN pip install prompt-toolkit==3.0.5
RUN pip install ptyprocess==0.6.0
RUN pip install pybtex==0.23.0
RUN pip install Pygments==2.6.1
RUN pip install pylint==2.5.2
RUN pip install pyparsing==2.4.7
RUN pip install pyrsistent==0.16.0
RUN pip install python-dateutil==2.8.1
#RUN pip install PyYAML==5.3
RUN pip install pyzmq==19.0.1
RUN pip install rise==5.6.1
RUN pip install scipy==1.4.1
RUN pip install Send2Trash==1.5.0
RUN pip install six==1.14.0
#RUN pip install terminado==0.8.3
RUN pip install testpath==0.4.4
RUN pip install toml==0.10.1
RUN pip install torch==1.4.0
RUN pip install torchdiffeq==0.0.1
RUN pip install torchvision==0.5.0
RUN pip install tornado==6.1.0
RUN pip install tqdm==4.42.1
RUN pip install traitlets==4.3.3
RUN pip install typed-ast==1.4.1
RUN pip install virtualenv-clone==0.5.4
RUN pip install wcwidth==0.2.5
RUN pip install webencodings==0.5.1
RUN pip install wrapt==1.12.1
RUN pip install zipp==3.1.0
RUN pip install scikit-learn==0.23
